name: Junip Dewan
description:
    
about: Junip is a Software Engineer at Promobi Technologies with almost 2 years of experience in Ruby, ROR, Vue and modern JS. He is a fast learner who can learn and implement new things on the fly. He is a dedicated and hard working version with a love of coding and solving hard problems.

    

master_repo: false
url: " "
markdown: kramdown
highlighter: rouge
subdomain_slug: dark-paper
# make on_subdomain false if using on a root domain
on_subdomain: true


plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           "Junip Dewan"
  avatar:         "https://avatars0.githubusercontent.com/u/19765255?s=240&v=4"
  email:          "junip.dewan@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: https://twitter.com/junipd2
  github: https://github.com/junipdewan
  stackexchange: https://stackoverflow.com/users/7432239/junip-dewan?tab=profile
  linkedin: https://www.linkedin.com/in/junipdewan/
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
